### ISSUE TITLE
Getting warnings on the browser

### ISSUE THREAD

**Issue by JoeKarlsson** [coeda/React-Kanban#11]
`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>. See CardItem > p > ... > div.`

and

`Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.`

![screen shot 2016-11-01 at 10 18 28 am](https://cloud.githubusercontent.com/assets/4650739/19905851/91e0c762-a01c-11e6-80bd-e2b198fc6e49.png)

**Comment by coeda** [comment]
cleared warnings, set default value correctly implemented
